### ISSUE TITLE
Amrutha: Suggestions on assignments

### ISSUE THREAD

**Issue by mmarun** [mmarun/java_training#1]
Read the Log4J documentation and use the logger to :

1. Print messages to the console (Screen)
2. Print messages in to the log file.

Use the Log4j logger to print the message "Hello There"

**Comment by amruthasudeesh** [comment]
already added. please have a look in this link: https://github.com/mmarun/java_training/blob/main/Students/Amrutha/session8/mavenDemo/src/main/java/org/demo/MathOperation.java . updated code is added only under student
