### ISSUE TITLE
Shreesh: Assignment Feedback

### ISSUE THREAD

**Issue by mmarun** [mmarun/java_training#10]
**Session 9** 
Assignment is missing. Please add the same.

**Session 10**
Assignment is missing. Please add the same.

**Session 11**
1. Add main class into the src directory. 
2. Unit tests are missing.

**Session13**
1. Unit tests are missing
2. Name the main class as AppMain or Main. Runner is okay but the AppMain and Main are conventional.

**Other assignments are missing**

**Comment by joshishreesh** [comment]
I was absent up to session 9. That's why I was unable to complete the session 9 assignment

**Comment by mmarun** [comment]
Read the assignments from Assignment.txt and Readme.txt respective session
folders.
Also make a point to add all assignments in respective session folders.

**Comment by joshishreesh** [comment]
Session 9 and 10 showing the same assignments. Session 9 assignments committed
Session 13 includes the session 12 assignment
Still having an issue with Unit Testing. I tried to use it in Assignment 9

**Comment by mmarun** [comment]
Closing
